# Generated by Django 4.0.5 on 2022-07-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='desc',
        ),
    ]
