# Generated by Django 4.0.5 on 2022-07-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_remove_destination_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
